apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-detro-do-container
          name: segundo-volume
    - name: jenkins
      image: jenkins:alpine
      volumeMounts:
        - mountPath: /volume-detro-do-container
          name: segundo-volume
  volumes:
    - name: segundo-volume
      hostPath:
        path: /home/segundo-volume
        type: DirectoryOrCreate